### ISSUE TITLE
(UI) Grouping UI

### ISSUE THREAD

**Issue by NineNineFive** [NineNineFive/PathfindingProject#23]
See if we should use Pane, Grid or whatever

**Comment by JonatanRytter** [comment]
Borderpane med canvas, button og enten Choicebox eller radiobuttons. Skal have fundet ud af et hack til scrollbars når windowsize er for lille.

**Comment by JonatanRytter** [comment]
Ellers primarystage.setResizeable(false);

**Comment by JonatanRytter** [comment]
Didly done
